# Interface
UserRepository: {
  shape: class
  style: {fill: "#f0f0f0"; stroke: "#000000"}
  +getById(id: number): string <<abstract>>
}

# Classes
MySQLUserRepository: {
  shape: class
  +getById(id: number): string
}

UserRepositoryFactory: {
  shape: class
  +getUserRepository(): UserRepository <<static>>
}

UserService: {
  shape: class
  -userRepository: UserRepository
  +constructor()
  +getById(id: number): string
}

# Relationships
UserRepository -> MySQLUserRepository: implements
UserService -> UserRepository: depends
UserService -> UserRepositoryFactory: uses
UserRepositoryFactory -> MySQLUserRepository: creates
UserService -> MySQLUserRepository: depends {
  style: {
    stroke: orange
    stroke-dash: 3
    stroke-width: 5
  }
}
